spring.application.name=docMind

spring.datasource.url=jdbc:mysql://localhost:3306/docmind
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

file.upload-dir=uploads

jwt.secret=YnJvd25iZW5kaGl0YW5ncnlwcml2YXRlbWVvcmlnaW5hbGRvb3JzaGFraW5nYXBhcnQ=
jwt.expiration=86400000

spring.ai.openai.api-key=open-ai-key

spring.data.redis.host=hosttttt
spring.data.redis.port=1111222
spring.data.redis.username=default
spring.data.redis.password=your_password

spring.ai.vectorstore.redis.initialize-schema=true

server.port=8080